### ISSUE TITLE
Application exits silently

### ISSUE THREAD

**Issue by jcbritobr** [wieslawsoltes/ColorPicker#16]
Hello, I exported an BaseLight.xaml file and put inside my application and setup it as follow:
```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             x:Class="MyApp.App">
    <Application.Styles>
        <!-- <FluentTheme Mode="Light"/> -->
        <StyleInclude Source="resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"/>
        <StyleInclude Source="resm:MyApp.BaseLight.xaml?assembly=MyApp"/>
    </Application.Styles>
</Application>
```

Above is the application structure

![image](https://user-images.githubusercontent.com/6579862/107262035-d3359780-6a1e-11eb-8152-7fe4a85aac93.png)

But this change makes the application exits silently without an error.

Avalonia version - 0.10
latest ThemeEditor
dotnet 5.0

**Comment by wieslawsoltes** [comment]
what is your `MyApp.BaseLight.xaml` and what is your csproj

**Comment by jcbritobr** [comment]
Here are the files. In App.xaml i just commented the others to use de default theme.

[BaseLight.zip](https://github.com/wieslawsoltes/ThemeEditor/files/5991636/BaseLight.zip)


[App.xaml..zip](https://github.com/wieslawsoltes/ThemeEditor/files/5991645/App.xaml.zip)
[MyApp.zip](https://github.com/wieslawsoltes/ThemeEditor/files/5991647/MyApp.zip)

**Comment by wieslawsoltes** [comment]
Please try version 0.10.13, I have added some fixes and refactored code.
