### ISSUE TITLE
Double precision error when opening color picker

### ISSUE THREAD

**Issue by karanveersp** [wieslawsoltes/ColorPicker#18]
Hi
I've just downloaded and tried to use the ThemeEditor on a windows 10, net6.0 machine.

As soon as I click on any of the options that bring up the color picker, the application exits.

Upon downloading the source and running the debugger, I found that certain values are failing validation checks.

For example, when I click on the Background Color, the alpha validation immediately fails with an alpha value of `100.00000000000001`.

```cs
private static bool ValidateAlpha(double alpha)
{
    if (alpha < 0.0 || alpha > 100.0)
    {
        throw new ArgumentException("Invalid Alpha value.");
    }
    return true;
}
```

Similarly for Foreground Color, where the `ValidateValue` method raises an exception for value `-1.4210854715202004E-14` soon as I click it.

From what I understand, making the `double` types into a `decimal` is one way of fixing these floating point errors.
Maybe there's some other way to validate the values or constrain them?

**Comment by wieslawsoltes** [comment]
Please try version 0.10.13, I have added value coercion.
