### ISSUE TITLE
HSL support

### ISSUE THREAD

**Issue by KillyMXI** [wieslawsoltes/ColorPicker#25]
Many times, when I interact with colors in various software - I want to use HSL color space to adjust colors. It fits my needs better than HSV, but it most often is ignored by developers and not acknowledged as a necessity.

Lightness and Saturation of HSL are more closely correlated to physical properties I need to adjust (Lightness - can go lighter and darker for any color, Saturation - from "single" wavelength of pure hue to even distribution of gray color) - this allows accurate single-slider adjustments.
HSV, while has simpler math underneath, doesn't have as meaningful sliders and mostly regarded for better color range on 2D palette.

Being implemented in controls like this will hopefully make it available in more applications.

**Comment by wieslawsoltes** [comment]
Not planned.
